name: codacy-coverage-reporter

on: ["push"]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    name: phpunit
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - name: PHPUnit tests
      uses: php-actions/phpunit@v3
      env:
        XDEBUG_MODE: coverage
      with:
        configuration: phpunit.xml
        php_extensions: xdebug
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: clover.xml
    - name: Make code coverage badge
      uses: timkrase/phpunit-coverage-badge@v1.2.1
      with:
        coverage_badge_path: output/coverage.svg
        push_badge: false
    - name: Git push to image-data branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./output
        publish_branch: image-data
        github_token: ${{ secrets.GITHUB_TOKEN }}
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
